// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArKpWEkEOQEnD4oVUdHLabT0Fpq19BKLU',
    appId: '1:72054995149:web:29d463bcafc1ad740c5184',
    messagingSenderId: '72054995149',
    projectId: 'training-sns-app-3e0f4',
    authDomain: 'training-sns-app-3e0f4.firebaseapp.com',
    storageBucket: 'training-sns-app-3e0f4.firebasestorage.app',
    measurementId: 'G-MT7CB2L3DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa4665jMV2wUNQYhEQn4zbHXp64pVtMy0',
    appId: '1:72054995149:android:b2f6d7cd07c61fa20c5184',
    messagingSenderId: '72054995149',
    projectId: 'training-sns-app-3e0f4',
    storageBucket: 'training-sns-app-3e0f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARX3zC7DvL7AbptsS5CzlRhHt-JAWgf1A',
    appId: '1:72054995149:ios:5668e4f0e166b6d70c5184',
    messagingSenderId: '72054995149',
    projectId: 'training-sns-app-3e0f4',
    storageBucket: 'training-sns-app-3e0f4.firebasestorage.app',
    iosBundleId: 'com.example.trainSnsApp',
  );

}