// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJNccYZcZNIh8Ct_V57iDTI4P0oQze6s',
    appId: '1:538872327654:web:2b88a1fab2746b872a3a27',
    messagingSenderId: '538872327654',
    projectId: 'habittrackerapp-5a157',
    authDomain: 'habittrackerapp-5a157.firebaseapp.com',
    storageBucket: 'habittrackerapp-5a157.firebasestorage.app',
    measurementId: 'G-3JP645M3WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBszI18yTwMfzT8zkonYlXaFShm_s4XxIU',
    appId: '1:538872327654:android:a525d7e2cf83e7d12a3a27',
    messagingSenderId: '538872327654',
    projectId: 'habittrackerapp-5a157',
    storageBucket: 'habittrackerapp-5a157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vGl_d59Q73AB3Kj6Nsu2vpdjP_OznJo',
    appId: '1:538872327654:ios:78067cee1d7794732a3a27',
    messagingSenderId: '538872327654',
    projectId: 'habittrackerapp-5a157',
    storageBucket: 'habittrackerapp-5a157.firebasestorage.app',
    iosBundleId: 'com.example.trainSnsApp',
  );
}
